In [1]:
import pandas as pd
import numpy as np
    

# pandas data types panel series and data frame 

## Data represented in tabular way
## can handle missing Data
## Great for Data analysis with big Datatsets and various file types
## series is an 1 d array capable of storing many dtypes 
## can Reshape datasets, Slice,subset and Merginging Joining

## Series 1D 

In [2]:
sr1 = pd.Series(range(1,5),['A','B','c','D'])

print(type(sr1))
print(sr1['B'])
print(sr1[1])

print()
print(sr1)

<class 'pandas.core.series.Series'>
2
2

A    1
B    2
c    3
D    4
dtype: int64


In [3]:
dic = {'key1':123,'key2':456}
ddf = pd.DataFrame(dic, index = ['A'])

npdf = pd.Series(np.frombuffer(b'kushan',dtype = 'S1'))
npdf2 = pd.Series(np.frombuffer(b'vickys',dtype ='S2'))
print(npdf)
print(npdf2)

0    b'k'
1    b'u'
2    b's'
3    b'h'
4    b'a'
5    b'n'
dtype: bytes8
0    b'vi'
1    b'ck'
2    b'ys'
dtype: bytes16


In [4]:
l= np.asarray([2,3])
l1 = np.asarray([[2,3],[4,5]])
l2=pd.Series(l,index = ['A','B'])
l2.array

<PandasArray>
[2, 3]
Length: 2, dtype: int32

## Data Frame

In [86]:
pd.Series(dic)


In [5]:
# SOME USEFUL FUNCTIONS
l= np.asarray([2,3])
l1 = np.asarray([[2,3],[4,5]])
l2=pd.Series(l,index = ['A','B'],name ='SeriesL2')
l3 = pd.DataFrame(l1,index=['row1','row2'],columns = ['c1','c2'])
print('hell')
print(l2.array)
print(l3.index)
print(l3.shape)
print(l2.name)
print(l3.ndim)
print(l3.values)
print(l2+2)
l2.shape
A.describe()
A.shape
A.isnull()
A.isnull.sum()#finds all null values
pd.set_option('display.max_columns',6)
pd.set_option('display.max_rows',16)

hell
<PandasArray>
[2, 3]
Length: 2, dtype: int32
Index(['row1', 'row2'], dtype='object')
(2, 2)
SeriesL2
2
[[2 3]
 [4 5]]
A    4
B    5
Name: SeriesL2, dtype: int32


NameError: name 'A' is not defined

In [6]:
l2.__add__(2)

A    4
B    5
Name: SeriesL2, dtype: int32

## DataFrame

In [7]:
A = pd.read_csv(r'C:\=IMPORT S\data.csv')
type(A)

pandas.core.frame.DataFrame

In [8]:
A[(A['weight_class']=='Lightweight')&(A['title_bout']>=True)].head(3)

R_fighter       B_fighter       Referee        date  \
204  Khabib Nurmagomedov  Justin Gaethje  Jason Herzog  2020-10-24   
470        Tony Ferguson  Justin Gaethje     Herb Dean  2020-05-09   
737  Khabib Nurmagomedov  Dustin Poirier  Marc Goddard  2019-09-07   

                                       location Winner  title_bout  \
204  Abu Dhabi, Abu Dhabi, United Arab Emirates    Red        True   
470                  Jacksonville, Florida, USA   Blue        True   
737  Abu Dhabi, Abu Dhabi, United Arab Emirates    Red        True   

    weight_class  B_avg_KD  B_avg_opp_KD  ...  R_win_by_Decision_Unanimous  \
204  Lightweight  0.437500      0.015625  ...                            6   
470  Lightweight  0.875000      0.031250  ...                            3   
737  Lightweight  0.260986      0.008057  ...                            6   

     R_win_by_KO/TKO  R_win_by_Submission  R_win_by_TKO_Doctor_Stoppage  \
204                2                    4                             0   
470                3                    6                             2   
737                2                    3                             0   

     R_Stance  R_Height_cms  R_Reach_cms  R_Weight_lbs  B_age  R_age  
204  Orthodox        177.80       177.80         155.0   31.0   32.0  
470  Orthodox        180.34       193.04         155.0   31.0   36.0  
737  Orthodox        177.80       177.80         155.0   30.0   30.0  

[3 rows x 144 columns]

In [9]:
aj = np.array([[[2,3,4,5],[5,6,7,8]],[[1,3,6,5],[2,7,4,8]]]).reshape(2,8)
B = pd.DataFrame(aj,index =[x for x in range(1,3)],columns =[x for x in range(1,9)])
A = pd.read_csv(r'C:\=IMPORT S\data.csv')

## ! Indexing using [], loc[], iloc[] and column_name

## 1) using [start:end:step ] this is kinds like head and tail 

In [10]:
B[0:2:1] # here we only slice rows out[start:end(exclusive):step]

1  2  3  4  5  6  7  8
1  2  3  4  5  5  6  7  8
2  1  3  6  5  2  7  4  8

In [11]:
print(B[0:1])
print(B[::2])

   1  2  3  4  5  6  7  8
1  2  3  4  5  5  6  7  8
   1  2  3  4  5  6  7  8
1  2  3  4  5  5  6  7  8


## 2) using column_names Df['column_name'] 
## if multiple columns use sunblist Df[['c1','c2']]

In [12]:
B[[1,2,7,8]]

1  2  7  8
1  2  3  7  8
2  1  3  4  8

In [13]:
A[['R_fighter','B_fighter','Referee']].head(3)

R_fighter        B_fighter        Referee
0  Adrian Yanez    Gustavo Lopez  Chris Tognoni
1  Trevin Giles    Roman Dolidze      Herb Dean
2   Tai Tuivasa  Harry Hunsucker      Herb Dean

## 3) using loc for sclicing by row index number

In [14]:
A.loc[0:6:2]

R_fighter        B_fighter         Referee        date  \
0   Adrian Yanez    Gustavo Lopez   Chris Tognoni  2021-03-20   
2    Tai Tuivasa  Harry Hunsucker       Herb Dean  2021-03-20   
4  Marion Reneau    Macy Chiasson      Mark Smith  2021-03-20   
6     Song Kenan      Max Griffin  Keith Peterson  2021-03-20   

                 location Winner  title_bout       weight_class  B_avg_KD  \
0  Las Vegas, Nevada, USA    Red       False       Bantamweight  0.000000   
2  Las Vegas, Nevada, USA    Red       False        Heavyweight       NaN   
4  Las Vegas, Nevada, USA   Blue       False  WomenBantamweight  0.125000   
6  Las Vegas, Nevada, USA   Blue       False       Welterweight  0.046875   

   B_avg_opp_KD  ...  R_win_by_Decision_Unanimous  R_win_by_KO/TKO  \
0         0.000  ...                            0                1   
2           NaN  ...                            1                3   
4         0.000  ...                            1                2   
6         0.125  ...                            1                3   

   R_win_by_Submission  R_win_by_TKO_Doctor_Stoppage  R_Stance  R_Height_cms  \
0                    0                             0  Orthodox        170.18   
2                    0                             0  Southpaw        187.96   
4                    2                             0  Orthodox        167.64   
6                    0                             0  Orthodox        182.88   

   R_Reach_cms  R_Weight_lbs  B_age  R_age  
0       177.80         135.0   31.0   27.0  
2       190.50         264.0   32.0   28.0  
4       172.72         135.0   29.0   43.0  
6       180.34         170.0   35.0   31.0  

[4 rows x 144 columns]

## 3) using iloc for sclicing by both row and column index number

In [15]:
A.iloc[0:6:2,0:3]

R_fighter        B_fighter        Referee
0   Adrian Yanez    Gustavo Lopez  Chris Tognoni
2    Tai Tuivasa  Harry Hunsucker      Herb Dean
4  Marion Reneau    Macy Chiasson     Mark Smith

In [16]:
A.iloc[0:6:2,3::-2] 

date        B_fighter
0  2021-03-20    Gustavo Lopez
2  2021-03-20  Harry Hunsucker
4  2021-03-20    Macy Chiasson

In [17]:
A.iloc[0:6:2,5::-2] 

Winner        date        B_fighter
0    Red  2021-03-20    Gustavo Lopez
2    Red  2021-03-20  Harry Hunsucker
4   Blue  2021-03-20    Macy Chiasson

###  Above while slicing columns after , [3 :: -2] while reversing(::) the first argument is start index | :: | second argument is while going in reverse from index mentiioned in 1st argument, how many no should it skip

In [18]:
A.head(1)

R_fighter      B_fighter        Referee        date  \
0  Adrian Yanez  Gustavo Lopez  Chris Tognoni  2021-03-20   

                 location Winner  title_bout  weight_class  B_avg_KD  \
0  Las Vegas, Nevada, USA    Red       False  Bantamweight       0.0   

   B_avg_opp_KD  ...  R_win_by_Decision_Unanimous  R_win_by_KO/TKO  \
0           0.0  ...                            0                1   

   R_win_by_Submission  R_win_by_TKO_Doctor_Stoppage  R_Stance  R_Height_cms  \
0                    0                             0  Orthodox        170.18   

   R_Reach_cms  R_Weight_lbs  B_age  R_age  
0        177.8         135.0   31.0   27.0  

[1 rows x 144 columns]

## Note :- use df.values to convert stuff to NDARRAY

In [19]:
print(A.values.shape)
print(A.values.ndim)

(6012, 144)
2


In [20]:
B.values

array([[2, 3, 4, 5, 5, 6, 7, 8],
       [1, 3, 6, 5, 2, 7, 4, 8]])

### Use isnull for filtering null values and use isnull().sum() for finding all null values

In [21]:
A.isnull().sum==0

False

In [22]:
A.isnull().sum()

R_fighter         0
B_fighter         0
Referee          32
date              0
location          0
               ... 
R_Height_cms      4
R_Reach_cms     406
R_Weight_lbs      2
B_age           172
R_age            63
Length: 144, dtype: int64

### use value_counts to get values and how many times are they repeated aand in which rows

In [60]:
A['date'].value_counts()

2016-11-19    25
2014-10-04    23
2014-05-31    22
2014-08-23    21
2014-06-28    21
              ..
1994-09-09     6
1998-03-13     6
2002-06-22     6
1996-09-20     6
2000-04-14     6
Name: date, Length: 550, dtype: int64

In [63]:
B[4].value_counts()

5    2
Name: 4, dtype: int64

In [62]:
B

1  2  3  4  5  6  7  8
1  2  3  4  5  5  6  7  8
2  1  3  6  5  2  7  4  8

### use Unique to find out no of unique values

In [66]:
B[4].unique() #only 1 unique value in column 4 of B df that is 5

array([5])

In [3]:
aj = np.array([[[2,3,4,5],[5,6,7,8]],[[1,3,6,5],[2,7,4,8]]]).reshape(2,8)
B = pd.DataFrame(aj,index =[x for x in range(1,3)],columns =[x for x in range(1,9)])
A = pd.read_csv(r'C:\=IMPORT S\data.csv')

# String IO and reading CSV json etc

In [25]:
import pandas as pd
from io import StringIO
import numpy as np
import os

In [26]:
textdemo = ('A,B,C\n''1,2,3\n''4,5,6') 

In [27]:
StringIO(textdemo)#making a string Io object

In [28]:
pdmade = pd.read_csv(StringIO(textdemo))# when we read any csv file it gets converted into stringio so e passed stringIo object

In [29]:
pdmade.to_csv('pdmade') #making a csv file out of string io object

In [30]:
pdmade = pd.read_csv(StringIO(textdemo),usecols= ['A','B'],index_col='A',dtype=int)
pdmade.dtypes

B    int32
dtype: object

In [31]:
pdmade = pd.read_csv(StringIO(textdemo),index_col='A',dtype={'A':int,'B':str})
pdmade.dtypes

B    object
C     int64
dtype: object

In [32]:
av =pd.read_csv(StringIO('Name,AGE,Roll\n''Sai,23,101\n''Vijay,33,22'),index_col='Roll')

In [33]:
av['Sex'] = 'Male'
av

Name  AGE   Sex
Roll                  
101     Sai   23  Male
22    Vijay   33  Male

## JSON 

In [34]:
# importing module
import pandas as pd

exercise = '''{
    "Duration": {
        "0": 60,
        "1": 60,
        "2": 60,
        "3": 45,
        "4": 45,
        "5": 60
    },
    "Pulse": {
        "0": 110,
        "1": 117,
        "2": 103,
        "3": 109,
        "4": 117,
        "5": 102
    },
    "Calories": {
        "0": 409,
        "1": 479,
        "2": 340,
        "3": 282,
        "4": 406,
        "5": 300
    }
}'''
bv= pd.read_json(exercise)
bv

Duration  Pulse  Calories
0        60    110       409
1        60    117       479
2        60    103       340
3        45    109       282
4        45    117       406
5        60    102       300

In [35]:
bv= pd.read_json(exercise,orient='records')
bv

Duration  Pulse  Calories
0        60    110       409
1        60    117       479
2        60    103       340
3        45    109       282
4        45    117       406
5        60    102       300

In [36]:
bv= pd.read_json(exercise,orient='index')
bv

0    1    2    3    4    5
Duration   60   60   60   45   45   60
Pulse     110  117  103  109  117  102
Calories  409  479  340  282  406  300

In [37]:
pd.read_json('{"name":["tim","cooke"],"Age":["5","3"]}')
# when you make a json string object it must be in a dictionary format inside '{}'
#values in a sunlist
#'{"key":["value1","value2"]}'



name  Age
0    tim    5
1  cooke    3

In [52]:
NA = pd.read_json('{"name":["tim","cooke"],"Age":["5","3"]}')

In [53]:
NA.loc[2] = ['jake',23]

In [63]:
NA.rename(index={0:'Zero',2:'Two'} , inplace = True)

In [66]:
NA

name  Age
Zero    tim    5
1     cooke    3
Two    jake   23

In [7]:
l2 = [1,2,[3,4],[5,6,7]]
l1 = []
for i in l2:
    if isinstance(i,int):
        l1.append(i)
    else:
        for j in i:
            l1.append(j)
            
        

In [8]:
l1

[1, 2, 3, 4, 5, 6, 7]

In [15]:
l3 = np.array(l2)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_25056\734563163.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  l3 = np.array(l2)


In [22]:
l4 = l3.flatten('C')

In [23]:
l4

array([1, 2, list([3, 4]), list([5, 6, 7])], dtype=object)

In [28]:
d2 =list(pd.core.common.flatten(l2))

In [29]:
print(d2)

[1, 2, 3, 4, 5, 6, 7]
