# Numpy :-

# Numpy or Numerical Python is used for working with huge ass arrays with data type ndarray (nd means N dimensional)
## These arrays were made using C language
## array are faster than lists and are not seprated by  ( , ) like lists are, list contents are called ITEMS while array contents are called ELEMENTS
## list can have multiple data types while array only holds 1 datatype values
## if strings are mentioned with integers, dtype will change to string


## 1) Creating arrays 

In [2]:
import numpy as np

### numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
### first is mandtory argument, dtype can be str , int , boinary
### order = C means Row major and F means 'Column major aka fortron
#### make a multi 2d array and try C and F, C takes values rowmajor wise ( reads first row then goes to 2nd)  and other reads 1st column the second column

In [3]:
ar  = np.array([[1,2],[3,5]], order='F') # using array() extra argument dtype

In [4]:
tup = (12,34,35,111)
atp = np.array((12,32))
atp2 = np.array(tup)
print(atp,atp2)

[12 32] [ 12  34  35 111]


### frombuffer(), asarray(), arrange(), linspace(), fromiter()

### arange :-  works like range(start, end,skip) end is end is exclusive (for 10 give 11)

In [5]:
ar1 = np.arange(2,13,2)#using arange(), start value end value nos to skip + dtype

In [6]:
ar1

array([ 2,  4,  6,  8, 10, 12])

### linspace is like arrange but give only n number of elements withing range 
### arguments (start value , end value, how many equally distributed values from start to end)
### 3rd argument determines how many elements will be there in a array

In [7]:
ar2 = np.linspace(2,10,4)# start value , end value, how many equally distributed values from start to end

In [8]:
ar2

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

NameError: name 'fromtier' is not defined

In [10]:
np.fromiter([1,23,4,56],'int',count=2)

array([ 1, 23])

## The np.asarray() function in NumPy is a utility function that converts input data into a NumPy array. It can take various types of input as its first argument, including lists, tuples, strings, and existing NumPy arrays (ndarray).

Here's how the np.asarray() function works:

If the input data is already a NumPy array (ndarray), the function will return the input array as-is without creating a new copy. This is useful when you want to ensure that the input is already in ndarray format, or when you want to avoid unnecessary copying of data.

If the input data is a list, tuple, or string, np.asarray() will create a new NumPy array and copy the data from the input into the array. The resulting array will be 1-dimensional (1D) unless the input data has multiple dimensions.

If the input data is nested (e.g., a list of lists), np.asarray() will attempt to create a multi-dimensional array with appropriate shape.

In [11]:

# Input is a list
lst = [1, 2, 3, 4]
arr_from_list = np.asarray(lst,dtype= 'str', order=None, )
print(arr_from_list)  # Output: [1 2 3 4]

# Input is a tuple
tpl = (5, 6, 7, 8)
arr_from_tuple = np.asarray(tpl)
print(arr_from_tuple)  # Output: [5 6 7 8]

# Input is a string
string_data = "hello"
arr_from_string = np.asarray(string_data)
print('\n',arr_from_string)  # Output: 'hello' (treated as a 0-dimensional array)

# Input is a NumPy array (ndarray)
existing_array = np.array([9, 10, 11, 12])
arr_from_existing_array = np.asarray(existing_array)
print(arr_from_existing_array)  # Output: [ 9 10 11 12]

# Input is a nested list (2D)
nested_list = [[1, 2], [3, 4]]
arr_from_nested_list = np.asarray(nested_list,dtype=None, order='C')
print('\n',arr_from_nested_list)
# Output:
# array([[1, 2],
#        [3, 4]])


['1' '2' '3' '4']
[5 6 7 8]

 hello
[ 9 10 11 12]

 [[1 2]
 [3 4]]


### Frombuffer gives 1d array using any pre existing buffer object (means It can be bytes, bytearray, or any object exposing the buffer interface.)
### Interpret a buffer as a 1-d array.
### frombuffer(buffer, dtype=float, count=-1, offset=0, *, like=None) 
### dtype = the data type of elements you want for string give buffer as b'text_string' and dtype = 'S1'
### count end point , offset starting point

In [9]:
## we will use a string and an tuple named tup for example
tup = (12,34,35,111)
af = np.frombuffer(b'jaiHo', dtype = 'S1', count=3, offset=0)

try :
    af2 = np.frombuffer(tup, dtype = 'S1', count=3, offset=0)
    
except TypeError as E:
    print(E)
finally:
    print('NO list , tuple can be passed ')
    
    
try :
    print(tup, af2 , af)
    
except NameError  as E2:
    print(E2)    
    
finally :
    print('\n',af)

a bytes-like object is required, not 'tuple'
NO list , tuple can be passed 
name 'af2' is not defined

 [b'j' b'a' b'i']


In [10]:
ar2 # only 4 elements are there

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

##  Initialising arrays using logspace, full,eye, zeros , zeros_like, ones, full and ones_like functions

In [11]:
ar3= np.zeros((5,2)) # makes arrays using shape of desired array in arguments fills it with zeros

In [12]:
ar4 = np.zeros_like((5,2)) # takes the provided array as an  example and not as a shape of array , then fill zero

In [13]:
dd =np.array([[[2,3],[4,5]],[[6,7],[7,8]],[[9,10],[11,12]]]) # this a 3D array

In [14]:
ar44 = np.zeros_like(dd) # can also mention array name

In [15]:
print(' np.zeros_like((5,2)) = \n',ar4,"\n \n np.zeros((5,2)) = \n", ar3 ,'\n \n np.zeros_like(dd) = \n',ar44)
print("\n is escape char for newline")

 np.zeros_like((5,2)) = 
 [0 0] 
 
 np.zeros((5,2)) = 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 
 
 np.zeros_like(dd) = 
 [[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]

 is escape char for newline


In [4]:


# Generate an array of 10 values evenly spaced on a base-2 logarithmic scale from 1 to 1024
result = np.logspace(start=0, stop=10, num=10, base=2.0)

print(result)


[1.00000000e+00 2.16011948e+00 4.66611616e+00 1.00793684e+01
 2.17726400e+01 4.70315038e+01 1.01593667e+02 2.19454460e+02
 4.74047853e+02 1.02400000e+03]


In [12]:
np.eye(4),

(array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),)

In [13]:
 np.eye(4,3,k = -2) ,  np.eye(4,3,k = 1)

(array([[0., 0., 0.],
        [0., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [9]:
full23 = np.full((2,4),23) #Return a new array of given shape and type, filled with `fill_value`.  23 is fill value


## Reshape, ndim, ndtype, nshape, nsize

In [10]:
full23

array([[23, 23, 23, 23],
       [23, 23, 23, 23]])

In [11]:
full23.shape# returns shape of array as a tuple

(2, 4)

In [5]:
np.reshape(fullarr,(8,1))

array([[23],
       [23],
       [23],
       [23],
       [23],
       [23],
       [23],
       [23]])

In [16]:
full23.ndim # returns no of dimension of array

2

In [17]:
full23.dtype # returns elements data type

dtype('int32')

In [19]:
full23.size # returns total no of elements in the array

8

In [18]:
dd.dtype # returns data type in C language ( int32 means int is  <32 in  size, u11 means text less than 11 in size)

dtype('int32')

In [19]:
dd.size # counts no of elements in array

12

## Splitting arrays / slicing arrays

In [164]:
demo = np.full((3,3,3),2)
test = np.array([[[2,5,6],[7,5,3],[5,3,1]] , [[2,4,6],[7,1,3],[5,8,1]] , [[1,4,6],[7,9,3],[5,8,1]]])
 # DIAGONAL function gives diagonal values from an array can get upper and lower diagonals above and below using k function

In [174]:
print(demo)
print('demo shape : ', demo.shape)
print('demo shape : ', demo.ndim)
#lets try to get indicing and slicing

dd = demo + test
print('dd shape : ', dd.shape)
print('dd shape : ', dd)

[[[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]]
demo shape :  (3, 3, 3)
demo shape :  3
dd shape :  (3, 3, 3)
dd shape :  [[[ 4  7  8]
  [ 9  7  5]
  [ 7  5  3]]

 [[ 4  6  8]
  [ 9  3  5]
  [ 7 10  3]]

 [[ 3  6  8]
  [ 9 11  5]
  [ 7 10  3]]]


In [170]:
dd 

array([[[ 4,  7,  8],
        [ 9,  7,  5],
        [ 7,  5,  3]],

       [[ 4,  6,  8],
        [ 9,  3,  5],
        [ 7, 10,  3]],

       [[ 3,  6,  8],
        [ 9, 11,  5],
        [ 7, 10,  3]]])

In [180]:
print(dd[1,0:3,1])


[ 6  3 10]


In [86]:
ddd.reshape(3,2)

array([[ 1,  5],
       [ 9,  2],
       [ 6, 10]])

### %timeit[ code] tells timme to run code

In [107]:
%timeit [np.zeros((2,3))]

256 ns ± 1.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [109]:
ab = [i for i in range(1,10,2) ]

In [110]:
ab

[1, 3, 5, 7, 9]

## concatenate, stack and split 

In [14]:
import numpy as np

In [15]:
c= np.array([[2 ,3, 4],[ 5, 6, 7]])
cc= np.array([[ 8 , 9 ,10 ],[ 11 , 12,13]])

In [16]:
print(c)
print(c.shape)
print()
print(cc)

[[2 3 4]
 [5 6 7]]
(2, 3)

[[ 8  9 10]
 [11 12 13]]


In [6]:

print(np.concatenate((c,cc),axis =1))
print(np.concatenate((c,cc),axis =1).shape)
print()
print(np.concatenate((c,cc),axis =0).shape)
print()
print(np.concatenate((c,cc),axis =0))

[[ 2  3  4  8  9 10]
 [ 5  6  7 11 12 13]]
(2, 6)

(4, 3)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [7]:
print(np.stack((c,cc),axis =1))
print(np.stack((c,cc),axis =1).shape)
print()
print(np.stack((c,cc),axis =0).shape)
print()
print(np.stack((c,cc),axis =0))

[[[ 2  3  4]
  [ 8  9 10]]

 [[ 5  6  7]
  [11 12 13]]]
(2, 2, 3)

(2, 2, 3)

[[[ 2  3  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]]


In [8]:
print(np.vstack((c,cc)))
print()
print(np.dstack((c,cc)))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]

[[[ 2  8]
  [ 3  9]
  [ 4 10]]

 [[ 5 11]
  [ 6 12]
  [ 7 13]]]


## lets Split some shit 

In [9]:
np.array_split(c,3)

[array([[2, 3, 4]]), array([[5, 6, 7]]), array([], shape=(0, 3), dtype=int32)]

In [10]:
np.hsplit(c,3)

[array([[2],
        [5]]),
 array([[3],
        [6]]),
 array([[4],
        [7]])]

In [17]:
c

array([[2, 3, 4],
       [5, 6, 7]])

## nditer and ndnumerate

In [18]:
for i in cc:
    
    for l in i:
        print(l)

8
9
10
11
12
13


In [19]:
for i in c:
    print(i)
    for l in i:
        print(l)

[2 3 4]
2
3
4
[5 6 7]
5
6
7


In [20]:
it=np.nditer(c ,flags =['buffered'], op_dtypes='S')

In [21]:
for i in it:
    print(i)

b'2'
b'3'
b'4'
b'5'
b'6'
b'7'


In [22]:
it=np.nditer(c)